-- 코드를 입력하세요
SELECT 
    b.AUTHOR_ID, 
    c.AUTHOR_NAME, 
    b.CATEGORY, 
    SUM(a.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK_SALES a
    JOIN BOOK b
    ON a.BOOK_ID = b.BOOK_ID
    JOIN AUTHOR c
    ON b.AUTHOR_ID = c.AUTHOR_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY 1, 3
ORDER BY 1, 3 DESC;