-- 코드를 입력하세요
SELECT a.ANIMAL_ID, a.NAME
FROM ANIMAL_INS a
    JOIN ANIMAL_OUTS b
    ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE b.ANIMAL_ID IS NOT NULL
ORDER BY DATEDIFF(b.DATETIME, a.DATETIME) + 1 DESC
LIMIT 2;