-- 코드를 입력하세요
SELECT a.CAR_ID, 
    a.CAR_TYPE,
    ROUND(a.DAILY_FEE * 30 * (1 - c.DISCOUNT_RATE / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR a
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c
    ON a.CAR_TYPE = c.CAR_TYPE
WHERE a.CAR_TYPE IN ('세단', 'SUV')
    AND c.DURATION_TYPE = '30일 이상'
    AND a.DAILY_FEE * 30 * (1 - c.DISCOUNT_RATE / 100) BETWEEN 500000 AND 2000000
    AND a.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01'
    )
ORDER BY FEE DESC, a.CAR_TYPE, a.CAR_ID DESC;