-- 코드를 입력하세요
SELECT HISTORY_ID
     , ROUND(DAILY_FEE  * (DATEDIFF(END_DATE, START_DATE) + 1) * COALESCE(1 - (DISCOUNT_RATE * .01),1),0) AS FEE
FROM
    (SELECT H.HISTORY_ID
        , H.CAR_ID
        , C.CAR_TYPE
        , C.DAILY_FEE
        , H.END_DATE
        , H.START_DATE
        ,CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
             WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
             WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
        ELSE NULL END AS DURATION_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C 
    ON C.CAR_ID = H.CAR_ID) A
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON A.CAR_TYPE = P.CAR_TYPE AND A.DURATION_DATE = P.DURATION_TYPE
WHERE A.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;
