-- 코드를 입력하세요
SELECT b.APNT_NO, a.PT_NAME, a.PT_NO, c.MCDP_CD, c.DR_NAME, b.APNT_YMD
FROM PATIENT a 
    JOIN APPOINTMENT b ON a.PT_NO = b.PT_NO 
    JOIN DOCTOR c ON c.DR_ID = b.MDDR_ID
WHERE 
    DATE_FORMAT(b.APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
    AND b.APNT_CNCL_YN = 'N' 
    AND c.MCDP_CD = 'CS'
ORDER BY b.APNT_YMD;