-- 코드를 입력하세요
SELECT b.APNT_NO, a.PT_NAME, a.PT_NO, c.MCDP_CD, c.DR_NAME, b.APNT_YMD
FROM PATIENT a 
    JOIN APPOINTMENT b ON a.PT_NO = b.PT_NO 
    JOIN DOCTOR c ON c.DR_ID = b.MDDR_ID
WHERE DATE_FORMAT(b.APNT_YMD, '%Y-%m-%d') != '2022-04-13' AND b.APNT_CNCL_YN = 'N'
ORDER BY b.APNT_YMD;


SELECT A.APNT_NO
     , P.PT_NAME
     , P.PT_NO
     , D.MCDP_CD
     , D.DR_NAME
     , A.APNT_YMD
FROM PATIENT P
    INNER JOIN APPOINTMENT A ON A.PT_NO = P.PT_NO
    INNER JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE A.APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59'
AND A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD