-- 코드를 입력하세요
SELECT a.APNT_NO, c.PT_NAME, c.PT_NO, b.MCDP_CD, b.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a
    JOIN DOCTOR b
    ON a.MDDR_ID = b.DR_ID
    JOIN PATIENT c
    ON a.PT_NO = c.PT_NO
WHERE b.MCDP_CD = 'CS' 
    AND a.APNT_CNCL_YN = 'N'
    AND DATE_FORMAT(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY 6;