-- 코드를 입력하세요
WITH RECURSIVE a AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM a
    WHERE HOUR < 23
)

SELECT
    a.HOUR,
    COUNT(ANIMAL_ID) AS COUNT
FROM a
    LEFT JOIN ANIMAL_OUTS b 
    ON a.HOUR = HOUR(b.DATETIME)
GROUP BY a.HOUR
ORDER BY a.HOUR;