-- 코드를 입력하세요
SELECT 
    b.BOOK_ID, 
    a.AUTHOR_NAME, 
    DATE_FORMAT(b.PUBLISHED_DATE, "%Y-%m-%d") PUBLISHED_DATE
FROM 
    (SELECT * 
     FROM BOOK
     WHERE CATEGORY='경제') b
     JOIN AUTHOR a 
     ON b.AUTHOR_ID = a.AUTHOR_ID
ORDER BY b.PUBLISHED_DATE;